IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'tchDb'))
USE tchDb;

GO

IF OBJECT_ID('Employees', 'u') IS NULL
CREATE TABLE Employees
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	TabNumber INT NOT NULL,
	UserId INT NOT NULL,
	PositionId INT NOT NULL,
	ColumnId INT NOT NULL

	FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
	FOREIGN KEY (PositionId) REFERENCES Positions(Id) ON DELETE NO ACTION,
	FOREIGN KEY (ColumnId) REFERENCES Columns(Id) ON DELETE NO ACTION
)