IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'tchDb'))
USE tchDb;

GO

IF OBJECT_ID('Users', 'u') IS NULL
CREATE TABLE Users
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	SurName NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	Patronymic NVARCHAR(50) NOT NULL,
	BirthDate DATETIME NOT NULL,
	LoginId INT

	FOREIGN KEY (LoginId) REFERENCES Logins(LoginId) ON DELETE CASCADE
)